### ISSUE TITLE
fails handling scoop aliases with multiple lines

### ISSUE THREAD

**Issue by phanirithvij2000** [KNOXDEV/scoop-backup#11]
Scoop aliases with multiple lines will generate a cli command with a single line and with no line seperators.

**E.g.**

An alias `multiline` manually edited (customized)
```powershell
# Summary: alias script with multiple lines
write-host first line
write-host second line
write-host etc..
```

```powershell
# Scoop-Backup's output for this alias
scoop alias add 'multiline' 'write-host first line write-host second line write-host etc..' 'alias script with multiple lines'
```

This is invalid.

So a possible fix might be handling newlines in powershell or encode/decode alias files to base64 (or some other format)

**Comment by KNOXDEV** [comment]
I don't immediately have a good idea. How would you go about creating a multi-line alias in the first place? Would you manually edit the scoop/config.json?

**Comment by phanirithvij** [comment]
In the config.json aliases dict has keys as the alias name and the alias script name as the value . The alias script is saved in the shims directory.

So I create a stub and go and edit the `shims/scoop-myalias.ps1`

**Comment by KNOXDEV** [comment]
This is a little bit niche since it kinda seems like scoop barely supports multi line aliases in the first place, but alright.

In that case, the solution would probably be to back up the shim files themselves. They would need to be probably encoded as base64 and embedded into the restore script, which would redump them into the shim directory. It's a bit involved.

**Comment by phanirithvij2000** [comment]
Yeah, calling external commands in one line which the scoop alias provides is good enough.
I think implementing alias files embedding is not really needed, just a good to have. I think this single line implementation is fine as of now, maybe just mention this issue, in this repo README. As multiline alias scripts are not supported by `scoop alias add` using external scripts as a workaround, which need to be separately backup .
