### ISSUE TITLE
I have changed the default installation path of scoop to D disk, and scoop-backup cannot be backed up.

### ISSUE THREAD

**Issue by xapohe** [KNOXDEV/scoop-backup#18]
Resolve-Path : 路径“C:\..\..\apps\scoop\current\lib”引用了基路径“C:”之外的项。
所在位置 D:\Applications\Scoop\apps\scoop-backup\current\scoop-backup.ps1:50 字符: 17
+ ... $scooplib = Resolve-Path "$($(Get-Command scoop).Source)\..\..\apps\s ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Resolve-Path]，PSArgumentException
    + FullyQualifiedErrorId : System.Management.Automation.PSArgumentException,Microsoft.PowerShell.Commands.ResolvePa
   thCommand

**Comment by KNOXDEV** [comment]
I've copied over the logic used to locate the scoop installation from [the bucket scripts](https://github.com/ScoopInstaller/Main/blob/master/bin/auto-pr.ps1).
```ps
if(!$env:SCOOP_HOME) { $env:SCOOP_HOME = Resolve-Path (scoop prefix scoop) }
    $scooplib = "$env:SCOOP_HOME\lib"
```

Update your scoop-backup installation and let me know if that works.

**Comment by xapohe** [comment]
scoop update scoop-backup
Updating one outdated app:
Updating 'scoop-backup' (0.2022.07.03 -> 0.2022.07.27)
Downloading new version
Downloading https://github.com/KNOXDEV/scoop-backup/archive/273c613464a2a22173482ba5408a43fdd6aa829a.zip (-1 B)...
Checking hash of 273c613464a2a22173482ba5408a43fdd6aa829a.zip ... ok.
Uninstalling 'scoop-backup' (0.2022.07.03)
Removing shim 'scoop-backup'.
Removing shim 'scoop-backup.cmd'.
Removing shim 'scoop-backup.ps1'.
Unlinking D:\Applications\Scoop\apps\scoop-backup\current
Installing 'scoop-backup' (0.2022.07.27) [64bit]
Loading 273c613464a2a22173482ba5408a43fdd6aa829a.zip from cache
Extracting 273c613464a2a22173482ba5408a43fdd6aa829a.zip ... done.
Linking D:\Applications\Scoop\apps\scoop-backup\current => D:\Applications\Scoop\apps\scoop-backup\0.2022.07.27
Creating shim for 'scoop-backup'.
Persisting backups
'scoop-backup' (0.2022.07.27) was installed successfully!

 scoop-backup
Failed to enumerate aliases, not backed up
backed up to: D:\Applications\Scoop\apps\scoop-backup\current\backups\backup-220728.ps1

 scoop-backup --compress
Failed to enumerate aliases, not backed up
backed up to: D:\Applications\Scoop\apps\scoop-backup\current\backups\backup-220728.bat

 查看文件夹有backup-220728.ps1和backup-220728.bat两个文件，这算备份失败吗？
Looking at the folder, there are only two files backup-220728.ps1 and backup-220728.bat. Does this count as a backup failure?

**Comment by KNOXDEV** [comment]
Nope, it's working now. The error message about aliases is referring to the fact that you don't have any. I'll make that message more clear in a separate issue. Thanks for testing it for me!
