### ISSUE TITLE
why its different - from scoop native

### ISSUE THREAD

**Issue by omaru-ok** [KNOXDEV/scoop-backup#19]
scoop has already introduced its own backup-import solution 

so why bother yours . 

if  u have any things to say . pleas also add it to README.md 

as , why use scoop-backup VS scoop native (export)

**Comment by KNOXDEV** [comment]
I agree. I created this package before scoop import and export were added and I think it would be better to encourage people to use the mainline solution. I'll edit the readme with the relevant information.

**Comment by OmiChrome** [comment]
thx for the work LMAO

🙏
