### ISSUE TITLE
scoop aliases

### ISSUE THREAD

**Issue by phanirithvij2000** [KNOXDEV/scoop-backup#6]
https://github.com/ScoopInstaller/Scoop/blob/master/libexec/scoop-alias.ps1

Some aliases like these can be set, https://gist.github.com/idleberg/e0872d37f792d3d969f4f3d24698773f

It would be great if these aliases can also be backed up

**Comment by KNOXDEV** [comment]
Nice, I'll go ahead and tackle this at some point this week, but bump this issue if I forget.

**Comment by phanirithvij2000** [comment]
reminding @KNOXDEV

**Comment by KNOXDEV** [comment]
Sorry for the lag, added. LMK if you notice any issues
